# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-iiOYG1SBcx5DMPvjyEE424hCqkyZo19
"""

import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="topsis",
    version="1.0.4",
    author="Shreya Jha",
    author_email="shreyajha2418@gmail.com",
    description="Package to calculate topsis score and rank them",
    long_description=long_description,
    long_description_content_type="text/markdown",
    license="MIT",
    url="https://github.com/shreyajha2410/topsis_shreya",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    packages=["topsis_shreya"],
    include_package_data=True,
    install_requires='pandas',
    entry_points={
        "console_scripts": [
            "topsis=topsis_shreya.topsis:main",
        ]
    },
)